# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39b4d04ce43abcb96fe9ba686ea59bdb4f2f0f67715b9449d6810d7661b96597d2e2ea4f6eb5f5445b1b84b66f1ad09b6ed009662d7f330de9e451e9a29f94e1

test:
  secret_key_base: 62ed03283c86ed3887ab4a6d2669ea8cb6322b874e43d19d1cf0e44551f8979abc5a08ba53f5257c33ad066ce35c16c89a925a4ff4a89a6b54e30e5a7be28147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
